version: 2

models:
  - name: stg_authority
    description: "Authorities are the legislation, administrative code, commission rulings or other policy documentation which are related to a specific policy/incentive in DSIRE. This table includes every Authority found in DSIRE. Not all entries in DSIRE have authorities associated with them."
    columns:
      - name: id
        description: "A unique identifier for each authority found in DSIRE."
        tests:
          - not_null
          - unique

      - name: program_id
        description: "Pulled from Program file. Each program in DSIRE has a unique identifier. Program_id in this file indicates the program in DSIRE that is associated with the authority."
        tests:
          - not_null

      - name: order
        description: "The order in which the authority appears within the hierarchy of authorities for a particular policy/incentive."

      - name: code
        description: "The statutory reference, bill number, commission ruling, etc."

      - name: website
        description: "Link to the legislation, commission ruling, etc."

      - name: enacted
        description: "Date the legislation, regulation, etc. was first enacted."

      - name: enactedtext
        description: "Text that may be needed to explain the enacted date, i.e. 'subsequently amended'. During data migration from the old version of DSIRE, the new system did not recognize some of our dates, and imported them into this field. We will be moving dates from this field to the enacted field as we update each individual program."

      - name: effective
        description: "Effective date for the legislation, regulation, etc."

      - name: effectivetext
        description: "Text that may be needed to explain the effective date. During data migration from the old version of DSIRE, the new system did not recognize some of our dates, and imported them into this field. We will be moving dates from this field to the effective field as we update each individual program."

      - name: expired
        description: "Date the legislation, regulation, etc. expires."

      - name: expiredtext
        description: "Text that may be needed to explain the expiration date. During data migration from the old version of DSIRE, the new system did not recognize some of our dates, and imported them into this field. We will be moving dates from this field to the expired field as we update each individual program."

      - name: file_key
        description: "Legacy data. Null."

      - name: file_name
        description: "Legacy data. Null."

  - name: stg_city
    description: "Every DSIRE entry with 'Local Government' as the implementing sector will have at least one city or county associated with it in the database. This table provides the unique identifier for each city. Used by zipcode file."
    columns:
      - name: id
        description: "A unique identifier for each city."
        tests:
          - not_null
          - unique

      - name: name
        description: "City name."
        tests:
          - not_null

      - name: state_id
        description: "Unique identifier for the city's state. State IDs can be found in the state table."
        tests:
          - not_null

  - name: stg_contact
    description: "Every entry in DSIRE lists a contact at the bottom of the page. This table collects all the contacts listed in DSIRE."
    columns:
      - name: id
        description: "A unique identifier for each contact."
        tests:
          - not_null
          - unique

      - name: created_ts
        description: "Date and time the contact was created in the database."

      - name: updated_ts
        description: "Date and time the contact was updated in the database."

      - name: first_name
        description: "First name of the contact."

      - name: last_name
        description: "Last name of the contact."

      - name: organization_name
        description: "Name of the organization the contact belongs to."

      - name: web_visible_default
        description: "Some contacts are only viewable to DSIRE staff. '1' in this field indicates that the contact is visible to the public."

      - name: phone
        description: "Phone number of the contact."

      - name: email
        description: "Email address of the contact."

      - name: website_url
        description: "Website URL of the contact."

      - name: address
        description: "Address of the contact."

      - name: city
        description: "City of the contact."

      - name: state_id
        description: "Unique identifier for the contact's state. State IDs can be found in the state file."

      - name: zip
        description: "ZIP code of the contact."

  - name: stg_county
    description: "Every DSIRE entry with 'Local Government' as the implementing sector will have at least one city or county associated with it in the database. This table provides the unique identifier for each county. Used by zipcode file."
    columns:
      - name: id
        description: "A unique identifier for each county."
        tests:
          - not_null
          - unique

      - name: name
        description: "County name."

      - name: state_id
        description: "Unique identifier for the county's state. State IDs can be found in the state file."
        tests:
          - not_null

  - name: stg_energy_category
    description: "All technologies in DSIRE are either renewable energy or energy efficiency technologies. This table provides a unique identifier to indicate whether a technology is a renewable energy or energy efficiency technology. Used by technology_category file."
    columns:
      - name: id
        description: "A unique identifier to indicate whether a technology is a renewable energy or energy efficiency technology."
        tests:
          - not_null
          - unique
